### ISSUE TITLE
Wanna join creating this awesome bot?

### ISSUE THREAD

**Issue by midascodebreaker** [setkyar/laravel-messenger-bot-management#1]
im also creating bot and using pimax, 
with env of https , using homestead.

my plan is to get all pages,
then create bots
then a bot will have a flow
the flow will have message and response.
and you can nest many message and response to a flow...

conditionals can match 
regex
exact word
include inside the message

im also planning to integrate other api...
for payment gateway...

let me know if you wanna help create this awesome project

**Comment by setkyar** [comment]
@midascodebreaker It does not related with this repo yet?
