### ISSUE TITLE
Could you please clarify further the verify_token and token step?

### ISSUE THREAD

**Issue by yazeed** [setkyar/laravel-messenger-bot-management#3]
Could you please clarify further the verify_token and token step? Are they both one and the same?

**Comment by setkyar** [comment]
Hi @yazeed 

They are difference. The `verify_token` is to verify your webhook. `token` is your Facebook page's access token.

**Comment by yazeed** [comment]
Thank you, that helped.

## 

Yazeed Al Oyoun

From: Set Kyar Wa Lar notifications@github.com notifications@github.com
Reply: setkyar/laravel-messenger-bot-management
reply@reply.github.com
reply@reply.github.com
Date: July 8, 2016 at 6:43:35 AM
To: setkyar/laravel-messenger-bot-management
laravel-messenger-bot-management@noreply.github.com
laravel-messenger-bot-management@noreply.github.com
CC: Yazeed Al Oyoun yazeed.aloyoun@gmail.com yazeed.aloyoun@gmail.com,
Mention mention@noreply.github.com mention@noreply.github.com
Subject:  Re: [setkyar/laravel-messenger-bot-management] Could you please
clarify further the verify_token and token step? (#3)

Hi @yazeed https://github.com/yazeed
