### ISSUE TITLE
Bot Loop command

### ISSUE THREAD

**Issue by pedro-c-oliveira** [setkyar/laravel-messenger-bot-management#4]
Hello,

I had install this app but after my "hi" message, bot answers me "hello" and takes in  a loop "Sorry. I don’t understand you."
in "app/Messenger/Helpers/Messenger.php" file, the foreach cycle assumes $command = ""; and it allways fall in default message.
I comment the line "$this->bot->send(new Message($message['sender']['id'], 'Sorry. I don’t understand you.'));" and after that seems work fine.
you think review this issue?

**Comment by setkyar** [comment]
@OrbitPodium - **Sorry. I don’t understand you.** is default message. If Bot does not know Questions. It will answer default message. If you don't want to show user to default message just comment it out [this line](https://github.com/setkyar/laravel-messenger-bot-management/blob/db4d086d0f2761b21599a16df9c03a4966b19854/app/Messenger/Helpers/Messenger.php#L60) or add/modify it yourself.

**Comment by pedro-c-oliveira** [comment]
@setkyar 
Yes this is the default message but if you start the chat and give a wrong command (see my attachment on red color) the bot answers the default message. After that, if you give right command (see my attachment on green color) the bot answers the respective message but after that, if there's no message from chat user, the bot goes to a loop in default message.
I have to comment out the default message to avoid the default message cycle.
Have you understand the issue? if the chat user gives no message the bot turns in default loop.

![chat_bot](https://cloud.githubusercontent.com/assets/17474012/18628427/168cad64-7e58-11e6-924e-656face43fa2.png)

**Comment by setkyar** [comment]
@OrbitPodium It worked fine on my one. But, I will check it out again. And will solve it out. 👍

**Comment by setkyar** [comment]
@OrbitPodium Does not loop in my side. 
![message does not loop](https://cloud.githubusercontent.com/assets/4435358/18629838/584867bc-7e8e-11e6-8104-e2b84d67a054.png)

**Comment by pedro-c-oliveira** [comment]
@setkyar I simply deploy the github repository and after that, made a composer install, make migrations and seed and voilá: the bot is working!
Could you have in mind a reason for this loop?
Of course i could code a workaround but i'm keeping understand why this happen on my installation.

**Comment by andreshg112** [comment]
I got the same error.
![captura de pantalla de 2017-03-29 22-55-22](https://cloud.githubusercontent.com/assets/15859884/24487173/89bfefaa-14d3-11e7-86a8-1139fa2352bf.png)

**Comment by andreshg112** [comment]
I've solved it using this:

`                    if (!empty($command)) {
                        // Handle command
                        $bot_answer = Answer::where('command', '=', strtolower($command))->first();

                        if ($bot_answer) {
                            $this->bot->send(new Message($message['sender']['id'], $bot_answer->answer));
                        } else {
                            //Default
                            $this->bot->send(new Message($message['sender']['id'], 'Sorry. I don’t understand you.'));
                        }
                    }`

**Comment by setkyar** [comment]
@OrbitPodium Thanks, I will check out and will fix on next release.
