### ISSUE TITLE
Is this supposed to work out of box?

### ISSUE THREAD

**Issue by seatechdev** [setkyar/laravel-messenger-bot-management#5]
Hi,  Is this supposed to work out of box with facebook bot?  I understand that I have to provide my token and secret.  I have tried using it but I am not having any success.   Can you please help?

**Comment by seatechdev** [comment]
I get infinite number of Sorry. I don’t understand you. Even though webhook is validated.    Spent 4 days trying to troubleshoot it but no success.

**Comment by setkyar** [comment]
@sbasi5576 Can you show me some screenshot?

**Comment by andreshg112** [comment]
I got the same error.
![captura de pantalla de 2017-03-29 22-55-22](https://cloud.githubusercontent.com/assets/15859884/24487058/d682e53c-14d2-11e7-9208-5ca51d1d67d0.png)

**Comment by andreshg112** [comment]
I've solved it using this:

                if (!empty($command)) {
                    // Handle command
                    $bot_answer = Answer::where('command', '=', strtolower($command))->first();

                    if ($bot_answer) {
                        $this->bot->send(new Message($message['sender']['id'], $bot_answer->answer));
                    } else {
                        //Default
                        $this->bot->send(new Message($message['sender']['id'], 'Sorry. I don’t understand you.'));
                    }
                }
